# Generated by Django 5.0.4 on 2024-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revu', '0004_userfollows'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='review_provided',
            field=models.BooleanField(default=False),
        ),
    ]
